default_install_hook_types: [pre-push]

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
        stages: [pre-push]
    # -   id: end-of-file-fixer
        # stages: [pre-push]
    -   id: trailing-whitespace
        stages: [pre-push]
-   repo: https://github.com/hhatto/autopep8
    rev: v2.3.1
    hooks:
    -   id: autopep8
        stages: [pre-push]
# -   repo: https://github.com/psf/black
#     rev: 22.10.0
#     hooks:
#     -   id: black
#         stages: [pre-push]
-   repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        stages: [pre-push]
-   repo: https://github.com/nbQA-dev/nbQA
    rev: 1.8.5
    hooks:
    -   id: nbqa-autopep8
        stages: [pre-push]
    # -   id: nbqa-black
    #     stages: [pre-push]
    -   id: nbqa-isort
        stages: [pre-push]
